version: '3'

services:
  haproxy:
    image: haproxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./snakeoil.pem:/usr/local/etc/certificate.pem
      - ./snakeoil.key:/usr/local/etc/certificate.pem.key
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
